/* AI Pulse — Article extras: prev/next nav, TOC, share buttons, keyboard shortcuts.
 *
 * Reads /manifest.json (auto-generated by publish.py) which lists every
 * article date in descending order. Computes prev/next URLs for the
 * current article based on its data-article-date attribute.
 */
(function () {
  "use strict";

  const currentDate = document.body.getAttribute("data-article-date");
  if (!currentDate) return; // not an article page

  // ──────────────────────────────────────────────────────────────────────
  // Prev / Next navigation
  // ──────────────────────────────────────────────────────────────────────
  function setupNav(manifest) {
    if (!manifest || !manifest.articles || !manifest.articles.length) return;

    // manifest.articles is sorted DESCENDING (newest first).
    const dates = manifest.articles.map((a) => a.date);
    const idx = dates.indexOf(currentDate);
    if (idx === -1) return;

    // "Previous" in reading sense = older article = HIGHER index
    // "Next" in reading sense = newer article = LOWER index
    const prevDate = dates[idx + 1] || null;
    const nextDate = dates[idx - 1] || null;

    document.querySelectorAll('.article-nav-btn[data-nav="prev"]').forEach((el) => {
      const dateEl = el.querySelector('[data-nav-date="prev"]');
      if (prevDate) {
        el.href = `${prevDate}.html`;
        if (dateEl) dateEl.textContent = formatShortDate(prevDate);
        el.classList.remove("article-nav-disabled");
      } else {
        el.classList.add("article-nav-disabled");
        el.removeAttribute("href");
        if (dateEl) dateEl.textContent = "—";
      }
    });

    document.querySelectorAll('.article-nav-btn[data-nav="next"]').forEach((el) => {
      const dateEl = el.querySelector('[data-nav-date="next"]');
      if (nextDate) {
        el.href = `${nextDate}.html`;
        if (dateEl) dateEl.textContent = formatShortDate(nextDate);
        el.classList.remove("article-nav-disabled");
      } else {
        el.classList.add("article-nav-disabled");
        el.removeAttribute("href");
        if (dateEl) dateEl.textContent = "—";
      }
    });

    // Keyboard shortcuts: ← prev, → next
    document.addEventListener("keydown", (e) => {
      // ignore when typing in inputs
      const tag = (e.target && e.target.tagName) || "";
      if (tag === "INPUT" || tag === "TEXTAREA") return;
      if (e.metaKey || e.ctrlKey || e.altKey) return;
      if (e.key === "ArrowLeft" && prevDate) {
        window.location.href = `${prevDate}.html`;
      } else if (e.key === "ArrowRight" && nextDate) {
        window.location.href = `${nextDate}.html`;
      }
    });
  }

  function formatShortDate(iso) {
    // iso = YYYY-MM-DD
    const [y, m, d] = iso.split("-").map(Number);
    const months = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
    return `${months[m-1]} ${d}`;
  }

  // ──────────────────────────────────────────────────────────────────────
  // Table of Contents
  // ──────────────────────────────────────────────────────────────────────
  function setupTOC() {
    const tocList = document.getElementById("toc-list");
    const tocAside = document.getElementById("article-toc");
    const tocOverlay = document.getElementById("article-toc-overlay");
    const tocTrigger = document.getElementById("toc-trigger-mobile");
    const tocClose = document.getElementById("toc-close-mobile");
    if (!tocList) return;

    const headers = document.querySelectorAll(
      ".article-content h2.content-section-header"
    );
    if (headers.length < 2) {
      if (tocAside) tocAside.style.display = "none";
      if (tocTrigger) tocTrigger.style.display = "none";
      return;
    }

    headers.forEach((h, i) => {
      const text = h.textContent.trim();
      const slug = `section-${i + 1}-${text
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/^-|-$/g, "")}`;
      h.id = slug;

      const li = document.createElement("li");
      const a = document.createElement("a");
      a.href = `#${slug}`;
      a.textContent = text;
      a.className = "toc-link";
      // Close drawer on mobile after click
      a.addEventListener("click", () => {
        if (window.innerWidth < 1024) closeDrawer();
      });
      li.appendChild(a);
      tocList.appendChild(li);
    });

    // Mobile drawer open/close
    function openDrawer() {
      tocAside && tocAside.classList.add("toc-open");
      tocOverlay && tocOverlay.classList.add("toc-overlay-open");
      document.body.style.overflow = "hidden";
    }
    function closeDrawer() {
      tocAside && tocAside.classList.remove("toc-open");
      tocOverlay && tocOverlay.classList.remove("toc-overlay-open");
      document.body.style.overflow = "";
    }
    if (tocTrigger) tocTrigger.addEventListener("click", openDrawer);
    if (tocClose) tocClose.addEventListener("click", closeDrawer);
    if (tocOverlay) tocOverlay.addEventListener("click", closeDrawer);
    document.addEventListener("keydown", (e) => {
      if (e.key === "Escape") closeDrawer();
    });

    // Highlight current section while scrolling
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          const link = tocList.querySelector(`a[href="#${entry.target.id}"]`);
          if (!link) return;
          if (entry.isIntersecting) {
            tocList.querySelectorAll(".toc-link.active").forEach((el) =>
              el.classList.remove("active")
            );
            link.classList.add("active");
          }
        });
      },
      { rootMargin: "-30% 0% -60% 0%" }
    );
    headers.forEach((h) => observer.observe(h));
  }

  // ──────────────────────────────────────────────────────────────────────
  // Share buttons
  // ──────────────────────────────────────────────────────────────────────
  function setupShare() {
    const url = window.location.href;
    const title = document.title.replace(" — AI Pulse", "");

    const copyBtn = document.querySelector('.share-btn[data-share="copy"]');
    if (copyBtn) {
      copyBtn.addEventListener("click", async () => {
        try {
          await navigator.clipboard.writeText(url);
          const label = copyBtn.querySelector(".share-label");
          const orig = label ? label.textContent : "";
          if (label) label.textContent = "Copied!";
          copyBtn.classList.add("share-copied");
          setTimeout(() => {
            if (label) label.textContent = orig;
            copyBtn.classList.remove("share-copied");
          }, 1500);
        } catch (e) {
          // Fallback: select text in a hidden input
          const ta = document.createElement("textarea");
          ta.value = url;
          document.body.appendChild(ta);
          ta.select();
          document.execCommand("copy");
          document.body.removeChild(ta);
        }
      });
    }

    const twitterBtn = document.querySelector('.share-btn[data-share="twitter"]');
    if (twitterBtn) {
      twitterBtn.href = `https://twitter.com/intent/tweet?text=${encodeURIComponent(
        title
      )}&url=${encodeURIComponent(url)}`;
    }

    const linkedinBtn = document.querySelector(
      '.share-btn[data-share="linkedin"]'
    );
    if (linkedinBtn) {
      linkedinBtn.href = `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(
        url
      )}`;
    }
  }

  // ──────────────────────────────────────────────────────────────────────
  // Main
  // ──────────────────────────────────────────────────────────────────────
  function init() {
    setupTOC();
    setupShare();

    // Fetch manifest, then wire prev/next + keyboard shortcuts
    fetch("../manifest.json", { cache: "no-cache" })
      .then((r) => (r.ok ? r.json() : null))
      .then((manifest) => setupNav(manifest))
      .catch(() => {
        // No manifest yet — hide nav buttons
        document
          .querySelectorAll(".article-nav-btn[data-nav]")
          .forEach((el) => el.classList.add("article-nav-disabled"));
      });
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", init);
  } else {
    init();
  }
})();
